# GolangCI-Lint configuration
# Docs: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - dupl          # Too strict for initial development
    - funlen        # Function length limits
    - gochecknoinits # Allow init functions
    - gocyclo       # Cyclomatic complexity
    - godox         # TODO/FIXME comments
    - gomnd         # Magic numbers

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/fd1az/arbitrage-bot

  gosec:
    excludes:
      - G104  # Audit errors not checked
      - G304  # File path provided as taint input

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-use-default: false
  exclude-case-sensitive: false
  max-issues-per-linter: 50
  max-same-issues: 5
  new: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - errcheck

    # Exclude known issues in generated files
    - path: mocks/
      linters:
        - all

    # Allow fmt.Print in main
    - path: cmd/
      linters:
        - forbidigo
